### PR TITLE
Add Go 1.13.4 with librdkafka 1.2.1

### PR DESCRIPTION
**Pull request by minitauros**
Not sure if this is the way to do it, but I guess it very probably is.

Also not sure if this makes the stuff automatically end up in Dockerhub.

Also not tested yet. Just opening the PR so that the next person wanting to make this sees that there's already some work done.

### CODE REVIEW

**Comment by minitauros** [comment]
@si-m is this the way to do it?

**Comment by Slijkhuis** [comment]
I think you still have to build and push the images yourself (/ from your local machine). No pipeline has been set up in this repository. Here, git is just used to share the code and to keep track of the things done locally.

**Comment by ricardogama** [comment]
Not enough new lines.

**Comment by si-m** [comment]
You need to build it yourself and then push it or setup the pipeline to do it on master 👁‍🗨.

**Review by si-m — APPROVED** [review]
I see the build in [docker-hub](https://hub.docker.com/layers/unitedwardrobe/golang-librdkafka/alpine3.10-golang1.13.4-librdkafka1.2.1/images/sha256-c2bc0a826da74ef21f477ff446f8f9e818b56dad1283d41ec5aba0bc97a0e7a7)

**Pull request merged**
